name: tamadrop_riverpod
description: "A new Flutter project."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  ffmpeg_kit_flutter_audio: ^6.0.3
  flutter:
    sdk: flutter
  flutter_flavor: ^3.1.3
  flutter_flavorizr: ^2.2.3
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  intl: ^0.20.1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  rive: ^0.13.20
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  uuid: ^4.5.1
  youtube_explode_dart: ^2.3.6
  http: ^1.2.2
  chewie: ^1.8.5
  video_player: ^2.9.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  pedantic_mono: ^1.29.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter_gen:
  output: lib/gen/
  line_length: 80
  assets:
    outputs:
      directory_path_enabled: true
  # Optional
  integrations:
    rive: true

flutter_native_splash:
  color: "#0094FF"
  image: assets/images/splash_icon.png

flutter_icons:
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  android: false

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: <DEV_PROJECT_NAME>
      android:
        applicationId: "" # ここにapplicationIdを設定
      ios:
        bundleId: "" # ここにbundleIdを設定
    prod:
      app:
        name: <PRODUCTION_PROJECT_NAME>
      android:
        applicationId: "" # ここにapplicationIdを設定
      ios:
        bundleId: "" # ここにbundleIdを設定

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
